### ISSUE TITLE
ModLog wrong title:

### ISSUE THREAD

**Issue by clovisd** [Repulser/bursting-cogs#10]
Hey!

I just installed ModLog plugin and the title for the Cog is showing as: 'invitemirror' on my .help menu.

```
invitemirror:
  modlogset      Change modlog settings
  modlogtoggle   toggle which server activity to log
```

I'm guessing this is a bug?

Thanks!

**Comment by ign0reme** [comment]
Just change the class name

**Comment by Jan200101** [comment]
It is still a bug.
WIll be a easy fix though

**Comment by Repulser** [comment]
Fixed.
