### ISSUE TITLE
ModLog Stopped Working

### ISSUE THREAD

**Issue by ViscousSummer88** [Repulser/bursting-cogs#11]
Hello, modlog has been a great tool and has been working up until the latest update where the cog refuses to log anything to the channel anymore. After uninstalling and reinstalling the cog and setting up it still doesn't operate as intended. Not showing bans, message deletes etc.

When trying to also enable !modlogset embed the following message shows "Error in command 'modlogset embed' - KeyError: 'embed'".

**Comment by haaddaa1** [comment]
same

**Comment by Repulser** [comment]
This is due to a change in the code, use modlogset disable, modlogset channel then toggle again.

**Comment by ViscousSummer88** [comment]
> This is due to a change in the code, use modlogset disable, modlogset channel then toggle again.

This didnt work.
