### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by JakeyPrime** [Repulser/bursting-cogs#25]
Any plans to update these cogs in the future? Most specifically the modlog? 
It seems to be the only half good modlog feature on the market right now for cogs, and it's super handy and easy to use, and would love to see it updates, as it seems to have lost some of its key features with updates to Discord over the past few months. 
Notably, the role and channel changes aren't being logged.

Thanks!

**Comment by Repulser** [comment]
I dont plan to continue support of these cogs, theyre badly made, i was merely experimenting with python and discord when i made them
